version: '3'
services:
  nuxt:
    build:
      context: front
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front:/nuxtjs
    tty: true
    working_dir: /nuxtjs
    command: sh -c "yarn install && yarn dev"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_COLLATION=utf8mb4_unicode_ci
      - HASH_NUMBER=12
    tty: true
  mysql:
    image: mysql
    ports: 
      - "3306:3306"
    volumes: 
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 1234:80
    volumes:
      - /sessions
volumes:
  mysql-data: