version: '3'
services:
  nuxt:
    build:
      context: front
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./front:/nuxtjs
    tty: true
    working_dir: /nuxtjs
    command: sh -c "yarn install && yarn dev"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    tty: true